# Training
DEFAULT_LOCAL_EPOCHS = 1
DEFAULT_BATCH_SIZE = 32
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_MOMENTUM = 0.9
DEFAULT_USE_GPU = True

# FL Process
DEFAULT_FL_ROUNDS = 5

# Datasets
SEED = 42
CIFAR10_SHARDS = 200
MNIST_SHARDS = 200
DEFAULT_TRAIN_SPLIT = 0.7

# Opacus
PRIVACY_TARGET_DELTA = 1e-5
PRIVACY_TARGET_EPSILON = 5.0

PRIVACY_NOISE_MULTIPLIER = 0.4
PRIVACY_MAX_GRAD_NORM = 1.2
