#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-scrub-fabric-volumes
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      name: job-scrub-fabric-volumes
    spec:
      restartPolicy: "Never"
      containers:
        - name: main
          image: busybox:latest
          command:
            - sh
            - -c
            - "rm -rvf /mnt/fabric-*/*"
          volumeMounts:
            - name: fabric-org0-volume
              mountPath: /mnt/fabric-org0
            - name: fabric-org1-volume
              mountPath: /mnt/fabric-org1
            - name: fabric-org2-volume
              mountPath: /mnt/fabric-org2
      volumes:
        - name: fabric-org0-volume
          persistentVolumeClaim:
            claimName: fabric-org0
        - name: fabric-org1-volume
          persistentVolumeClaim:
            claimName: fabric-org1
        - name: fabric-org2-volume
          persistentVolumeClaim:
            claimName: fabric-org2

