name: Fabric
version: "2.0.0"

caliper:
    blockchain: fabric

channels:
    - channelName: mainline
      contracts:
          - id: catalyst
    - channelName: shard1
      contracts:
          - id: models

organizations:
    - mspid: Org1MSP
      identities:
          certificates:
              - name: "User1"
                clientPrivateKey:
                    path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/79109ec815da7a82147bf993b9d8149a6838e2273ed9368e2cce516fc3c82f16_sk"
                clientSignedCert:
                    path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
          discover: true
    - mspid: Org2MSP
      identities:
          certificates:
              - name: "User1"
                clientPrivateKey:
                    path: "../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/a694290d6690eafff3f743621a6a3c6392615bd6b10c5b24bf453104ee4e720f_sk"
                clientSignedCert:
                    path: "../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml"
          discover: true
