name: Fabric
version: "2.0.0"

caliper:
    blockchain: fabric

channels:
    - channelName: mainline
      contracts:
          - id: catalyst
    - channelName: shard1
      contracts:
          - id: models

organizations:
    - mspid: Org1MSP
      identities:
          certificates:
              - name: "User1"
                clientPrivateKey:
                    path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk"
                clientSignedCert:
                    path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem"
      connectionProfile:
          path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
          discover: true
    - mspid: Org2MSP
      identities:
          certificates:
              - name: "User1"
                clientPrivateKey:
                    path: "../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk"
                clientSignedCert:
                    path: "../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem"
      connectionProfile:
          path: "../test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml"
          discover: true
