test:
    workers:
        type: local
        number: 2
    rounds:
        - label: Create models simuating participant training
          txDuration: 30
          rateControl:
              type: fixed-load
              opts:
                  transactionLoad: 3
          workload:
              module: workload/createModel.js
              arguments:
                  contractId: models
